### ISSUE TITLE
Modernizing

### ISSUE THREAD

**Issue by urbanjost** [arjenmarkus/old-programming-idioms#2]
Standardizing for portability,  Modernizing to improve the maintainability of the code, and 
making old code work because it contains old extensions or removed features all overlap 
but have unique issues.  One resource to draw on or perhaps to update and expand is

https://fortranwiki.org/fortran/show/Modernizing+Old+Fortran

**Comment by arjenmarkus** [comment]
Thanks, I will check it, the main goal was to document idioms that have
been used in the past and are still being found in source code. But some
guidance as how to modernise things is certainly within scope.

Regards,

Arjen

Op wo 28 jun 2023 om 10:35 schreef urbanjost ***@***.***>:

**Comment by arjenmarkus** [comment]
I have added a reference to the Wiki page. And added one somewhat obscure feature regarding I/O that I found there.

**Comment by urbanjost** [comment]
Looks good. Nice examples.  Would make an interesting set of test cases or examples for modernizing tools like SPAG.
